=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act1dtd.dtd
<!ELEMENT llistafactures (factures+)>
<!ELEMENT factures (factura+)>
<!ELEMENT factura (emissor)>
<!ELEMENT emissor (cif, nom, vendes?, nom_pagador, import)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT vendes (#PCDATA)>
<!ELEMENT nom_pagador (#PCDATA)>
<!ELEMENT import (#PCDATA)>

=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act1dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistafactures SYSTEM "act1dtd.dtd">
<llistafactures>
    <factures>
        <factura>
            <emissor>
                <cif>41617826F</cif>
                <nom>Paco</nom>
                <nom_pagador>Josep</nom_pagador>
                <import>4000</import>
            </emissor>
            <emissor>
                <cif>41617826F</cif>
                <nom>Paco</nom>
                <nom_pagador>Gerard</nom_pagador>
                <import>5000</import>
            </emissor>
        </factura>
    </factures>
</llistafactures>
