=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act2dtd.dtd
<!ELEMENT llistacursos (curs+)>
<!ELEMENT curs (alumnes+)>
<!ELEMENT alumnes (alumne+)>
<!ELEMENT alumne (DNI, nom, cognom, assignatures+)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT assignatures (#PCDATA)>
<!ELEMENT assignatures (assignatura+)>
<!ELEMENT assignatura (nom, codi, professor)>
<!ELEMENT professor (num_personal, nom, cognom)>
<!ELEMENT num_personal (#PCDATA)>
<!ELEMENT codi (#PCDATA)>

=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act2dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistacursos SYSTEM "act2dtd.dtd">
<llistacursos>
    <curs>
        <alumnes>
            <alumne>
                <DNI>41610725E</DNI>
                <nom>Pepe</nom>
                <cognom>Carreras</cognom>
                <assignatures>
                    <assignatura>
                        <nom>Catala</nom>
                        <codi>4758</codi>
                        <professor>
                            <num_personal>68776455</num_personal>
                            <nom>Jose</nom>
                            <cognom>Garcia</cognom>
                        </professor>
                    </assignatura>
                </assignatures>
            </alumne>
        </alumnes>
    </curs>
</llistacursos>
