=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act3dtd.dtd
<!ELEMENT llibreria (llibre | quadern | llapis)+>

<!ELEMENT llibre (#PCDATA)>
<!ELEMENT llibre titol CDATA #REQUIRED>

<!ELEMENT quadern (#PCDATA)>
<!ELEMENT quadern num_pagines CDATA #IMPLIED>

<!ELEMENT llapis (#PCDATA | numero)>
<!ELEMENT numero  (#PCDATA)>

=== 77adri/LMSGI/Garcia_Olives_Adria_pack4_dtd_ud3/act3dtd.xml
<?xml version="1.0"?>
<!DOCTYPE llibreria SYSTEM "act3dtd.dtd">
<llibreria>
    <llibre titol="El quijote"/>
    <quadern num_fulles="450"/>
    <llapis>
        <numero>4</numero>
    </llapis>
    <llibre titol="El principito"/>
    <llapis>
        <numero>2</numero>
    </llapis>
</llibreria>
