=== 77adri/LMSGI/Garcia_olives_adria_pack3_dtd/act1dtd.dtd
<!ELEMENT llistavendes (venda+)>
<!ELEMENT venda (import, comprador, venedor, data?, codiFactura)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT venedor (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT codiFactura (#PCDATA)>

=== 77adri/LMSGI/Garcia_olives_adria_pack3_dtd/act1dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistavendes SYSTEM "act1dtd.dtd">
<llistavendes>
    <venda>
        <import>1200.50</import>
        <comprador>ClientA</comprador>
        <venedor>VenedorX</venedor>
        <data>2023-02-15</data>
        <codiFactura>FAC123</codiFactura>
    </venda>
    <venda>
        <import>800.00</import>
        <comprador>ClientB</comprador>
        <venedor>VenedorY</venedor>
        <codiFactura>FAC456</codiFactura>
    </venda>
</llistavendes>
