=== 77adri/LMSGI/Garcia_olives_adria_pack3_dtd/act3dtd.dtd
<!ELEMENT entrega (lot+)>
<!ELEMENT lot (palet+)>
<!ELEMENT palet (nombreCaixes, contingut, pesPalet, formaManipulacio)>
<!ELEMENT contingut (component+)>
<!ELEMENT component (nom, procedencia?, numeroSerie, pes, unitatPes?)>
<!ELEMENT procedencia (pais+)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT numeroSerie (#PCDATA)>
<!ELEMENT pes (#PCDATA)>
<!ELEMENT unitatPes (#PCDATA)>
<!ELEMENT formaManipulacio (#PCDATA)>
<!ELEMENT nombreCaixes (#PCDATA)>
<!ELEMENT pesPalet (#PCDATA)>

=== 77adri/LMSGI/Garcia_olives_adria_pack3_dtd/act3dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrega SYSTEM "act3dtd.dtd">
<entrega>
    <lot>
        <palet>
            <nombreCaixes>20</nombreCaixes>
            <contingut>
                <component>
                    <nom>NouComponent</nom>
                    <procedencia>
                        <pais>Espanya</pais>
                        <pais>Fran√ßa</pais>
                    </procedencia>
                    <numeroSerie>ABC123</numeroSerie>
                    <pes>2.5</pes>
                    <unitatPes>quilos</unitatPes>
                </component>
                <component>
                    <nom>AltComponent</nom>
                    <numeroSerie>XYZ789</numeroSerie>
                    <pes>1.8</pes>
                </component>
            </contingut>
            <pesPalet>50.0</pesPalet>
            <formaManipulacio>Pallet</formaManipulacio>
        </palet>
    </lot>
</entrega>
